version: 2.1

jobs:
  test-java:
    docker:
      - image: cimg/openjdk:21.0
      - image: postgres:16
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: apichallengedb_test
    environment:
      SPRING_PROFILES_ACTIVE: test
      SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/apichallengedb_test
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    steps:
      - checkout

      - run:
          name: Wait for Postgres
          command: |
            for i in `seq 1 30`; do
              nc -z localhost 5432 && echo "Postgres is up" && break
              echo "Waiting for Postgres..."
              sleep 1
            done

      - run:
          name: Run integration tests with coverage
          command: mvn -Dtest=UserIntegrationTest -X test

      - run:
          name: List coverage files
          command: |
            ls -R
            echo "----"
            ls -l target || echo "no target dir"
            echo "----"
            ls -l target/jacoco.exec || echo "no jacoco.exec"


      - run:
          name: Upload coverage to Coveralls
          command: mvn -X coveralls:report -DrepoToken=$COVERALLS_REPO_TOKEN

      - store_test_results:
          path: target/surefire-reports

workflows:
  build-and-test:
    jobs:
      - test-java

    # - deploy:
    #     requires:
    #       - test-java
