version: 2.1

jobs:
  test-java:
    docker:
      # compare cimg/openjdk:21.0 vs maven:3.9.6-eclipse-temurin-21 vs gcr.io/distroless/java21 vs openjdk:13-jdk-alpine
      - image: cimg/openjdk:21.0
      - image: postgres:16
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: apichallengedb_test
    environment:
      SPRING_PROFILES_ACTIVE: test
      SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/apichallengedb_test
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    steps:
      - checkout

      - run:
          name: Wait for Postgres
          command: |
            for i in `seq 1 30`; do
              nc -z localhost 5432 && echo "Postgres is up" && break
              echo "Waiting for Postgres..."
              sleep 1
            done

      - run:
          name: Run integration tests with coverage
          command: mvn -Dtest=UserIntegrationTest clean verify

      - run:
          name: Upload coverage to Coveralls
          command: |
            curl -L https://coveralls.io/coveralls-linux.tar.gz | tar -xz
            ./coveralls --repo-token $COVERALLS_REPO_TOKEN \
              --file target/site/jacoco/jacoco.xml \
              --format jacoco

      - store_test_results:
          path: target/surefire-reports

workflows:
  build-and-test:
    jobs:
      - test-java

    # - deploy:
    #     requires:
    #       - test-java
